# Generated by Django 4.2.7 on 2023-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_aca_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID'), max_length=255, null=True, verbose_name='Student password'),
        ),
    ]
