# Generated by Django 4.2.7 on 2023-12-03 15:24

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default=django.db.models.fields.Field.value_from_object, max_length=255, null=True, verbose_name='Student password'),
        ),
    ]
