# Generated by Django 4.2.7 on 2023-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Will be id if blank', max_length=255, null=True, verbose_name='Student password'),
        ),
    ]
