# Generated by Django 4.2.7 on 2023-12-03 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date_ofj',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
