# Generated by Django 4.2.7 on 2023-12-03 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_date_ofj'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='levels',
            field=models.CharField(blank=True, choices=[('1', 'LEVEL 1'), ('2', 'LEVEL 2'), ('3', 'LEVEL 3'), ('4', 'LEVEL 4'), ('5', 'LEVEL 5')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Date_ofj',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
