# Generated by Django 4.2.7 on 2023-12-03 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Term',
            field=models.CharField(blank=True, choices=[('1', 'First term'), ('2', 'Second term')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ending_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='starting_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Date_ofj',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date of join'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Intructor name')),
                ('ins_course', models.ManyToManyField(blank=True, to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor'),
        ),
    ]
