# Generated by Django 4.2.7 on 2023-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_term_course_ending_date_course_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coden',
            field=models.CharField(default='palce holder', max_length=255, verbose_name='Code name'),
        ),
    ]
