# Generated by Django 4.2.7 on 2023-12-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attend',
        ),
    ]
